emoji = true
autocomplete = true

[[commit_types]]
name = "feat"
emoji = "âœ¨"
description = "Nueva caracterÃ­stica"

[[commit_types]]
name = "fix"
emoji = "ğŸ›"
description = "CorrecciÃ³n de errores"

[[commit_types]]
name = "docs"
emoji = "ğŸ“"
description = "Cambios en la documentaciÃ³n"

[[commit_types]]
name = "style"
emoji = "ğŸ’„"
description = "Cambios que no afectan al sentido del cÃ³digo"

[[commit_types]]
name = "refactor"
emoji = "â™»ï¸"
description = "Cambios de cÃ³digo que no corrigen errores ni aÃ±aden nueva funcionalidad."

[[commit_types]]
name = "remove"
emoji = "ğŸ§¹"
description = "Se elimina codigo o archivos"

[[commit_types]]
name = "perf"
emoji = "âš¡"
description = "Cambios de cÃ³digo que mejora el rendimiento"

[[commit_types]]
name = "test"
emoji = "âœ…"
description = "AÃ±ade tests o correge los existentes"

[[commit_types]]
name = "build"
emoji = "ğŸ“¦"
description = "Cambios que afectan al sistema de compilaciÃ³n o a dependencias externas"

[[commit_types]]
name = "ci"
emoji = "ğŸ¤–"
description = "Cambios en nuestros archivos de configuraciÃ³n y scripts de CI"

[[commit_types]]
name = "chore"
emoji = "â­•"
description = "Otros cambios que no modifican los archivos de src o de test"

[[commit_types]]
name = "revert"
emoji = "âª"
description = "Anula una confirmaciÃ³n anterior"